src/main/kotlin/com/project/goms/domain/outing/entity/OutingBlackList.kt

:fire: @Indexed 어노테이션 삭제

---

.github/workflows/CD.yml

- main에 push 될때만 CD 실행 하도록 변경하였습니다.
- main 브랜치에 push 될때만 CD.yml 스크립트 작업이 실행되도록 변경하였습니다.

🔀 :: main에 push 될때만 CD 실행

---

src/main/kotlin/com/project/goms/domain/outing/scheduler/OutingScheduler.kt

외출 디스코드 알림이 6시40분에 가던걸 6시20분으로 수정했습니다.

🔀 :: 외출 디스코드 스케줄러 시간 설정

---

src/main/kotlin/com/project/goms/domain/studentCouncil/presentation/StudentCouncilController.kt
src/main/kotlin/com/project/goms/domain/studentCouncil/usecase/DeleteOutingListUseCase.kt
src/main/kotlin/com/project/goms/global/security/SecurityConfig.kt

학생회에서 외출자를 삭제할 수 있는 기능 요구 사항 추가
학생회가 외출리스트에서 외출자를 삭제할 수 있는 기능을 구현했습니다.

 🔀 :: 학생회가 외출리스트에서 외출자를 삭제하는 기능 구현

---

src/main/kotlin/com/project/goms/domain/studentCouncil/presentation/StudentCouncilController.kt
src/main/kotlin/com/project/goms/domain/studentCouncil/usecase/DeleteOutingUseCase.kt
src/main/kotlin/com/project/goms/global/security/SecurityConfig.kt

클래스명 변경, security 추가
클래스명을 변경했습니다.
security에 값을 변경했습니다.

🔀 :: 외출자 삭제 로직 잘못된 부분 수정

---

src/main/kotlin/com/project/goms/global/security/SecurityConfig.kt

존재하지 않는 endpoint에 상태코드를 변경했습니다.
존재하지 않는 endpoint에 대한 상태코드를 404로 변경하였습니다.

🔀 :: 존재하지 않는 endpoint로 요청시 404 반환

---

src/main/kotlin/com/project/goms/domain/account/entity/Account.kt
src/main/kotlin/com/project/goms/domain/late/entity/Late.kt
src/main/kotlin/com/project/goms/domain/outing/entity/Outing.kt
src/main/kotlin/com/project/goms/domain/studentCouncil/entity/StudentCouncil.kt
src/main/kotlin/com/project/goms/global/entity/BaseIdxEntity.kt
src/main/kotlin/com/project/goms/global/entity/BaseUUIDEntity.kt

BaseIdxEntity와 BaseUUIDEntity를 생성했습니다.
생성한 것을 상속받아서 idx를 생성했습니다.

🔀 :: BaseIdxEntity, BaseUUIDEntity 생성

---

src/main/kotlin/com/project/goms/global/security/SecurityConfig.kt
src/main/kotlin/com/project/goms/global/security/handler/CustomAccessDeniedHandler.kt

존재하지 않은 api를 요청시 404를 반환하게 설정했습니다.

🔀 :: 404 반환하기

---

src/main/kotlin/com/project/goms/domain/studentCouncil/common/util/StudentCouncilConverter.kt
src/main/kotlin/com/project/goms/domain/studentCouncil/common/util/impl/StudentCouncilConverterImpl.kt
src/main/kotlin/com/project/goms/domain/studentCouncil/presentation/StudentCouncilController.kt
src/main/kotlin/com/project/goms/domain/studentCouncil/presentation/data/response/SearchOutingResponse.kt
src/main/kotlin/com/project/goms/domain/studentCouncil/usecase/SearchOutingUseCase.kt
src/main/kotlin/com/project/goms/domain/studentCouncil/usecase/dto/SearchOutingDto.kt

외출중인 학생을 검색하기 위한 기능을 구현 요구사항
현재 외출중인 학생을 검색하는 기능을 구현했습니다

🔀 :: 외출중인 학생 검색하기 

---

src/main/kotlin/com/project/goms/domain/outing/common/util/OutingConverter.kt
src/main/kotlin/com/project/goms/domain/outing/common/util/impl/OutingConverterImpl.kt
src/main/kotlin/com/project/goms/domain/outing/presentation/OutingController.kt
src/main/kotlin/com/project/goms/domain/outing/presentation/data/response/SearchOutingResponse.kt
src/main/kotlin/com/project/goms/domain/outing/usecase/SearchOutingUseCase.kt
src/main/kotlin/com/project/goms/domain/outing/usecase/dto/SearchOutingDto.kt
src/main/kotlin/com/project/goms/domain/studentCouncil/common/util/StudentCouncilConverter.kt
src/main/kotlin/com/project/goms/domain/studentCouncil/common/util/impl/StudentCouncilConverterImpl.kt
src/main/kotlin/com/project/goms/domain/studentCouncil/presentation/StudentCouncilController.kt
src/main/kotlin/com/project/goms/domain/studentCouncil/presentation/data/response/SearchOutingResponse.kt
src/main/kotlin/com/project/goms/global/security/SecurityConfig.kt

+ 학생 검색에 대한 권한 변경
+ 현재 외출중인 학생을 검색할 수 있는 권한을 학생에게도 주었습니다.

🔀 :: 현재 외출중인 학생을 검색할 수 있는 권한을 학생에게도 부여

---

src/main/kotlin/com/project/goms/domain/account/common/util/impl/AccountConverterImpl.kt
src/main/kotlin/com/project/goms/domain/account/presentation/data/response/ProfileResponse.kt
src/main/kotlin/com/project/goms/domain/account/usecase/QueryAccountProfileUseCase.kt
src/main/kotlin/com/project/goms/domain/account/usecase/dto/ProfileDto.kt

+ 프로필을 반환할때 반환되는 값을 추가하였습니다.
+ 프로필을 반환할때 authority도 같이 반환되게 구현했습니다.

🔀 :: 프로필 반환 값 추가하기

---

src/main/kotlin/com/project/goms/domain/outing/common/util/impl/OutingConverterImpl.kt
src/main/kotlin/com/project/goms/domain/outing/presentation/OutingController.kt
src/main/kotlin/com/project/goms/domain/outing/usecase/SearchOutingUseCase.kt

- 외출 학생 이름이 null로 온다면 전체 학생을 반환하도록 구현하였습니다.
- 빠른 구현을 위해서 if문으로 필터 처리를 하였지만, 아직도 n + 1 문제가 발생합니다. 
추후 query dsl을 사용하여 join으로 연관된 account 까지 같이 가져오게 리펙토링을 진행하면 될거 같습니다.

🔀 :: 외출 학생 null이면 전체 학생 반환하기

---

src/test/kotlin/com/project/goms/domain/outing/SearchOutingUseCaseTest.kt

+ 테스트 코드를 작성하였습니다.
+ 현재 외출중인 학생을 검색하는 테스트 코드를 작성하였습니다.

🔀 :: 현재 외출중인 학생 검색하기 테스트 코드 추가

---

src/main/kotlin/com/project/goms/domain/outing/entity/repository/OutingRepository.kt

+ OutingRepository의 타입을 변경하였습니다.
+ OutingRepository의 타입을 UUID에서 Long으로 변경하였습니다.

🔀 :: OutingRepository 타입 변경

---

src/test/kotlin/com/project/goms/domain/outing/ValidateOutingTimeUseCaseTest.kt

+ 테스트코드를 작성하였습니다.
+ 현재 외출 가능한 시간인지 Boolean값으로 구분하는 기능에 대한 테스트코드를 작성하였습니다.

🔀:: 현재 외출 가능한 시간인지 구분하는 기능 테스트 코드 작성

---

.github/workflows/CD-Dev.yml
.github/workflows/CD-Prod.yml

- 개발 서버의 CD가 필요하다고 생각하였습니다.
- 기존 CD 스크립트를 CD-Prod로 수정하고, 디스코드로 알림을 보낼때 보기 편하게 내용을 수정하였습니다.
- 개발 서버의 CD 스크립트를 추가하였습니다.

🔀 :: 개발 서버 CD 스크립트 추가

---

src/main/kotlin/com/project/goms/domain/outing/scheduler/OutingScheduler.kt

- 지각자 저장 시간을 변경하였습니다.
- 지각자 저장 시간을 25분에서 26분으로 변경하였습니다.

🔀 :: 지각자 저장 시간 저장

---

src/main/kotlin/com/project/goms/domain/notification/entity/DeviceToken.kt
src/main/kotlin/com/project/goms/global/security/SecurityConfig.kt

- notification api에 권한을 추가하였습니다.
- deviceToken의 redisHash에 이름을 지정하였습니다.

🔀 :: notification api 권한 추가

---

.github/workflows/CD-Prod.yml

- 클라우드 타입에서 제공하는 cd 스크립트로 변경하였습니다.

🔀 :: 클라우드 타입에서 제공하는 cd 스크립트로 변경

---

.github/workflows/CD-Prod.yml

🔀 :: cd 스크립트 이름 수정

---

.github/workflows/CD-Prod.yml

+ cd 스크립트에서 에러가 발생했습니다.
+ 환경변수명을 변경하였습니다.

🔀  :: cd 스크립트 수정

---

.github/workflows/CD-Prod.yml

+ gauth 로그인에서 에러가 발생했습니다.
+ 환경변수명을 변경하였습니다.

🔀  :: 환경변수명 변경
